// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmiqfkdgvixdmcqckihm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtaXFma2Rndml4ZG1jcWNraWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDE5MjcsImV4cCI6MjA2OTM3NzkyN30.H73KlJhCrLzYO3Cy9fyDA_PFuxM6442kspcmpU3uMww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});